version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    # depends_on:
    #   postgres:
    #     condition: service_healthy
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=person_db
    # healthcheck:
    #   test: pg_isready -U mydbuser -d mydbname
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5
 
    volumes:
      - pg_data:/var/lib/postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data: 