version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    # depends_on:
    #   postgres:
    #     condition: service_healthy
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=person_db
    # healthcheck:
    #   test: ["CMD", "mysqladmin","ping","-h","localhost"]
    #   timeout: 20s
    #   retries: 10  
    volumes:
      - pg_data:/var/lib/postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data: 