http:
  address: localhost
  port: :3000

logger:
  log_level: 'debug'

postgres:
  pg_host: postgesql
  pg_port: 5432
  pg_user: postgres
  pg_password: postgres
  pg_dbname: person_db
  PostgresqlSslmode: false
  PgDriver: pgx

