http:
  port: ':8080'

logger:
  log_level: 'debug'

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: person_db
  # PostgresqlSslmode: false
  # PgDriver: pgx

